### ISSUE TITLE
pyproject.toml: python-minifier as build-backend

### ISSUE THREAD

**Issue by nschloe** [dflook/python-minifier#42]
Modern Python projects define their build requirements in `pyproject.toml`, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
]
build-backend = "setuptools.build_meta"
```
It'd be nice addition of python-minifier could be defined as the builder, e.g.,
```toml
[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "python-minifier>=xyz",
]
build-backend = "python_minifier.build_meta"
```
to spit out minified package code.
